name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_with_unittests:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: submodule
      run: git submodule init; git submodule update
    - name: install-sdsl
      run: ./src/sdsl-lite/install.sh ~
    - name: make
      run: make
    - name: tests
      run: make test
