name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_with_unittests_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: submodule
      run: git submodule init; git submodule update
    - name: install-sdsl
      run: ./src/sdsl-lite/install.sh ~
    - name: make
      run: make all-ci-linux
    - name: tests
      run: make test-ci-linux

  build_with_unittests_macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: submodule
      run: git submodule init; git submodule update
    - name: install-sdsl
      run: ./src/sdsl-lite/install.sh ~
    - name: make
      run: make all-ci-macos
    - name: tests
      run: make test-ci-macos
